Agrega clase region
IslasGECI/islas pull request #2
Opened 2019-08-09 18:29 UTC by efren-cabrera

Esta tarea se encuentra en el renglón de Pruebas. Aquí se agregaron varios archivos que son necesarios para correr las pruebas.

2019-08-14 18:33 UTC, devarops requested changes

2019-08-14 18:33 UTC, evaristor commented on .travis.yml
> +  - py.test --cov-report term --cov=islas -v
¿No hay versión larga para argumento `-v` de `py.test`?

2019-08-14 18:33 UTC, evaristor commented on .travis.yml
> +  - py.test --cov-report term --cov=islas -v
Checa [esto](https://stackoverflow.com/a/41893170).

2019-08-19 16:26 UTC, efren-cabrera commented on .travis.yml
> +  - py.test --cov-report term --cov=islas -v
Listo

2019-08-19 17:32 UTC, merged