Crea clase region
IslasGECI/islas pull request #3
Opened 2019-08-09 19:56 UTC by efren-cabrera

Agrega clase que representa una región

2019-08-09 21:06 UTC, evaristor commented
Por favor indica en la descripción del _PR_ en cuál renglón se encuentra.

2019-08-09 21:06 UTC, devarops requested changes
Por favor indica en la descripción del _PR_ en cuál renglón se encuentra.

2019-08-09 21:18 UTC, devarops requested changes

2019-08-09 21:18 UTC, evaristor commented on islas/Region.py
> +        Arreglo con las coordenadas norte de todos los polígonos separados por
Parece que hay algo raro en esta descripción

2019-08-09 21:18 UTC, evaristor commented on islas/Region.py
> +        Arreglo con las coordenadas este de todos los polígonos separados por
Parece que hay algo raro en esta descripción

2019-08-09 21:18 UTC, evaristor commented on .travis.yml
> +  - py.test --cov-report term --cov=islas -v
¿Dado que estamos usando Python 3, tal vez convenga usar `pytest` en lugar de `py.test`?

2019-08-09 21:18 UTC, evaristor commented on .travis.yml
> +  - py.test --cov-report term --cov=islas -v
Creo que `--verbose` es la forma larha de `-v`

2019-08-19 16:41 UTC, efren-cabrera commented on .travis.yml
> +  - py.test --cov-report term --cov=islas -v
ya quedó

2019-08-19 16:41 UTC, efren-cabrera commented on islas/Region.py
> +        Arreglo con las coordenadas este de todos los polígonos separados por
listo

2019-08-19 16:41 UTC, efren-cabrera commented on islas/Region.py
> +        Arreglo con las coordenadas norte de todos los polígonos separados por
listo

2019-08-19 17:31 UTC, devarops approved these changes

2019-08-19 17:32 UTC, merged